/// initialize instructions
// You can write your code in this editor
lines = _a(
	_a("INSTRUCTIONS", noone),
	_a("CONTROL THE QUEEN BEE BY MOVING THE MOUSE AROUND", noone),
	_a("GAIN CONTROL OF MORE BEES BY DEFEATING AN ENEMY QUEEN BEE", noone),
	_a("WORKER BEES WILL BUILD THE HIVE WHILE YOU ARE AWAY TO INCREASE THE MAXIMUM AMOUNT OF BEES YOU CAN CONTROL", noone),
	_a("DEFEAT ALL FACTIONS TO WIN", noone),
	_a("IF YOUR QUEEN BEE DIES, GAME OVER", noone),
	_a("PRESS ESC TO GO BACK TO MAIN MENU", noone)
	)